/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendRealTimeRouteImport } from './routes/trend-real-time'
import { Route as IndexRouteImport } from './routes/index'

const TrendRealTimeRoute = TrendRealTimeRouteImport.update({
  id: '/trend-real-time',
  path: '/trend-real-time',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trend-real-time': typeof TrendRealTimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trend-real-time': typeof TrendRealTimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trend-real-time': typeof TrendRealTimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trend-real-time'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trend-real-time'
  id: '__root__' | '/' | '/trend-real-time'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrendRealTimeRoute: typeof TrendRealTimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trend-real-time': {
      id: '/trend-real-time'
      path: '/trend-real-time'
      fullPath: '/trend-real-time'
      preLoaderRoute: typeof TrendRealTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrendRealTimeRoute: TrendRealTimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
