/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendViraliRouteImport } from './routes/trend-virali'
import { Route as TrendRealTimeRouteImport } from './routes/trend-real-time'
import { Route as TrendEvergreenRouteImport } from './routes/trend-evergreen'
import { Route as TrendAttualiRouteImport } from './routes/trend-attuali'
import { Route as TiktokHashtagRouteImport } from './routes/tiktok-hashtag'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as InfluencerFeedRouteImport } from './routes/influencer-feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReputazioneBrandIndexRouteImport } from './routes/reputazione-brand.index'
import { Route as PianoEditorialeIndexRouteImport } from './routes/piano-editoriale.index'
import { Route as InfluencerIndexRouteImport } from './routes/influencer.index'
import { Route as FeedIndexRouteImport } from './routes/feed.index'
import { Route as CollabInstagramIndexRouteImport } from './routes/collab-instagram.index'
import { Route as CanaliInspoIndexRouteImport } from './routes/canali-inspo.index'
import { Route as AspiMonitoringIndexRouteImport } from './routes/aspi-monitoring.index'
import { Route as InfluencerIdRouteImport } from './routes/influencer.$id'
import { Route as EditorGraficoRubricaIdRouteImport } from './routes/editor-grafico.$rubricaId'
import { Route as CollabInstagramUsernameRouteImport } from './routes/collab-instagram.$username'
import { Route as CanaliInspoIdRouteImport } from './routes/canali-inspo.$id'
import { Route as AspiMonitoringIdRouteImport } from './routes/aspi-monitoring.$id'
import { Route as ApiPublicHooksTriggerSyncCanaliFeedRouteImport } from './routes/api/public/hooks/trigger-sync-canali-feed'
import { Route as ApiPublicHooksTriggerSyncAspiMonitoringRouteImport } from './routes/api/public/hooks/trigger-sync-aspi-monitoring'
import { Route as ApiPublicHooksTriggerDiscoveryPipelineRouteImport } from './routes/api/public/hooks/trigger-discovery-pipeline'
import { Route as ApiPublicHooksTopTiktokHashtagsRouteImport } from './routes/api/public/hooks/top-tiktok-hashtags'
import { Route as ApiPublicHooksTiktokOembedRouteImport } from './routes/api/public/hooks/tiktok-oembed'
import { Route as ApiPublicHooksTiktokHashtagPostsRouteImport } from './routes/api/public/hooks/tiktok-hashtag-posts'
import { Route as ApiPublicHooksSyncViralTrendsRouteImport } from './routes/api/public/hooks/sync-viral-trends'
import { Route as ApiPublicHooksSyncTrendingHashtagsRouteImport } from './routes/api/public/hooks/sync-trending-hashtags'
import { Route as ApiPublicHooksSyncTiktokHashtagRouteImport } from './routes/api/public/hooks/sync-tiktok-hashtag'
import { Route as ApiPublicHooksSyncInstagramCollabRouteImport } from './routes/api/public/hooks/sync-instagram-collab'
import { Route as ApiPublicHooksSyncCrossSourceTrendsRouteImport } from './routes/api/public/hooks/sync-cross-source-trends'
import { Route as ApiPublicHooksSyncBrandMentionsRouteImport } from './routes/api/public/hooks/sync-brand-mentions'
import { Route as ApiPublicHooksSyncAudioTrendsRouteImport } from './routes/api/public/hooks/sync-audio-trends'
import { Route as ApiPublicHooksSubmitManualRouteImport } from './routes/api/public/hooks/submit-manual'
import { Route as ApiPublicHooksRecordTopicVolumeRouteImport } from './routes/api/public/hooks/record-topic-volume'
import { Route as ApiPublicHooksRecheckViralEngagementRouteImport } from './routes/api/public/hooks/recheck-viral-engagement'
import { Route as ApiPublicHooksPollGmailRouteImport } from './routes/api/public/hooks/poll-gmail'
import { Route as ApiPublicHooksMonitorTopicsRouteImport } from './routes/api/public/hooks/monitor-topics'
import { Route as ApiPublicHooksListMonitoredTopicsRouteImport } from './routes/api/public/hooks/list-monitored-topics'
import { Route as ApiPublicHooksListInstagramContentUrlsRouteImport } from './routes/api/public/hooks/list-instagram-content-urls'
import { Route as ApiPublicHooksListCrossSourceTrendsRouteImport } from './routes/api/public/hooks/list-cross-source-trends'
import { Route as ApiPublicHooksListCanaliInspoTopicsRouteImport } from './routes/api/public/hooks/list-canali-inspo-topics'
import { Route as ApiPublicHooksLinkPreviewRouteImport } from './routes/api/public/hooks/link-preview'
import { Route as ApiPublicHooksImportAspiBulkRouteImport } from './routes/api/public/hooks/import-aspi-bulk'
import { Route as ApiPublicHooksGettySearchRouteImport } from './routes/api/public/hooks/getty-search'
import { Route as ApiPublicHooksFigmaImportRouteImport } from './routes/api/public/hooks/figma-import'
import { Route as ApiPublicHooksExtractKeywordsRouteImport } from './routes/api/public/hooks/extract-keywords'
import { Route as ApiPublicHooksExportXlsxRouteImport } from './routes/api/public/hooks/export-xlsx'
import { Route as ApiPublicHooksExportFeedPptxRouteImport } from './routes/api/public/hooks/export-feed-pptx'
import { Route as ApiPublicHooksDeleteTrendSubmissionRouteImport } from './routes/api/public/hooks/delete-trend-submission'
import { Route as ApiPublicHooksDeleteCanaleRouteImport } from './routes/api/public/hooks/delete-canale'
import { Route as ApiPublicHooksCheckTokenHealthRouteImport } from './routes/api/public/hooks/check-token-health'
import { Route as ApiPublicHooksApproveJobRouteImport } from './routes/api/public/hooks/approve-job'
import { Route as ApiPublicHooksAddClientChannelRouteImport } from './routes/api/public/hooks/add-client-channel'

const TrendViraliRoute = TrendViraliRouteImport.update({
  id: '/trend-virali',
  path: '/trend-virali',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendRealTimeRoute = TrendRealTimeRouteImport.update({
  id: '/trend-real-time',
  path: '/trend-real-time',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendEvergreenRoute = TrendEvergreenRouteImport.update({
  id: '/trend-evergreen',
  path: '/trend-evergreen',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendAttualiRoute = TrendAttualiRouteImport.update({
  id: '/trend-attuali',
  path: '/trend-attuali',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokHashtagRoute = TiktokHashtagRouteImport.update({
  id: '/tiktok-hashtag',
  path: '/tiktok-hashtag',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerFeedRoute = InfluencerFeedRouteImport.update({
  id: '/influencer-feed',
  path: '/influencer-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReputazioneBrandIndexRoute = ReputazioneBrandIndexRouteImport.update({
  id: '/reputazione-brand/',
  path: '/reputazione-brand/',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoEditorialeIndexRoute = PianoEditorialeIndexRouteImport.update({
  id: '/piano-editoriale/',
  path: '/piano-editoriale/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIndexRoute = InfluencerIndexRouteImport.update({
  id: '/influencer/',
  path: '/influencer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabInstagramIndexRoute = CollabInstagramIndexRouteImport.update({
  id: '/collab-instagram/',
  path: '/collab-instagram/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaliInspoIndexRoute = CanaliInspoIndexRouteImport.update({
  id: '/canali-inspo/',
  path: '/canali-inspo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AspiMonitoringIndexRoute = AspiMonitoringIndexRouteImport.update({
  id: '/aspi-monitoring/',
  path: '/aspi-monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerIdRoute = InfluencerIdRouteImport.update({
  id: '/influencer/$id',
  path: '/influencer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorGraficoRubricaIdRoute = EditorGraficoRubricaIdRouteImport.update({
  id: '/editor-grafico/$rubricaId',
  path: '/editor-grafico/$rubricaId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabInstagramUsernameRoute = CollabInstagramUsernameRouteImport.update({
  id: '/collab-instagram/$username',
  path: '/collab-instagram/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaliInspoIdRoute = CanaliInspoIdRouteImport.update({
  id: '/canali-inspo/$id',
  path: '/canali-inspo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AspiMonitoringIdRoute = AspiMonitoringIdRouteImport.update({
  id: '/aspi-monitoring/$id',
  path: '/aspi-monitoring/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTriggerSyncCanaliFeedRoute =
  ApiPublicHooksTriggerSyncCanaliFeedRouteImport.update({
    id: '/api/public/hooks/trigger-sync-canali-feed',
    path: '/api/public/hooks/trigger-sync-canali-feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTriggerSyncAspiMonitoringRoute =
  ApiPublicHooksTriggerSyncAspiMonitoringRouteImport.update({
    id: '/api/public/hooks/trigger-sync-aspi-monitoring',
    path: '/api/public/hooks/trigger-sync-aspi-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTriggerDiscoveryPipelineRoute =
  ApiPublicHooksTriggerDiscoveryPipelineRouteImport.update({
    id: '/api/public/hooks/trigger-discovery-pipeline',
    path: '/api/public/hooks/trigger-discovery-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTopTiktokHashtagsRoute =
  ApiPublicHooksTopTiktokHashtagsRouteImport.update({
    id: '/api/public/hooks/top-tiktok-hashtags',
    path: '/api/public/hooks/top-tiktok-hashtags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTiktokOembedRoute =
  ApiPublicHooksTiktokOembedRouteImport.update({
    id: '/api/public/hooks/tiktok-oembed',
    path: '/api/public/hooks/tiktok-oembed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTiktokHashtagPostsRoute =
  ApiPublicHooksTiktokHashtagPostsRouteImport.update({
    id: '/api/public/hooks/tiktok-hashtag-posts',
    path: '/api/public/hooks/tiktok-hashtag-posts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncViralTrendsRoute =
  ApiPublicHooksSyncViralTrendsRouteImport.update({
    id: '/api/public/hooks/sync-viral-trends',
    path: '/api/public/hooks/sync-viral-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncTrendingHashtagsRoute =
  ApiPublicHooksSyncTrendingHashtagsRouteImport.update({
    id: '/api/public/hooks/sync-trending-hashtags',
    path: '/api/public/hooks/sync-trending-hashtags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncTiktokHashtagRoute =
  ApiPublicHooksSyncTiktokHashtagRouteImport.update({
    id: '/api/public/hooks/sync-tiktok-hashtag',
    path: '/api/public/hooks/sync-tiktok-hashtag',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncInstagramCollabRoute =
  ApiPublicHooksSyncInstagramCollabRouteImport.update({
    id: '/api/public/hooks/sync-instagram-collab',
    path: '/api/public/hooks/sync-instagram-collab',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncCrossSourceTrendsRoute =
  ApiPublicHooksSyncCrossSourceTrendsRouteImport.update({
    id: '/api/public/hooks/sync-cross-source-trends',
    path: '/api/public/hooks/sync-cross-source-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBrandMentionsRoute =
  ApiPublicHooksSyncBrandMentionsRouteImport.update({
    id: '/api/public/hooks/sync-brand-mentions',
    path: '/api/public/hooks/sync-brand-mentions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncAudioTrendsRoute =
  ApiPublicHooksSyncAudioTrendsRouteImport.update({
    id: '/api/public/hooks/sync-audio-trends',
    path: '/api/public/hooks/sync-audio-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSubmitManualRoute =
  ApiPublicHooksSubmitManualRouteImport.update({
    id: '/api/public/hooks/submit-manual',
    path: '/api/public/hooks/submit-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecordTopicVolumeRoute =
  ApiPublicHooksRecordTopicVolumeRouteImport.update({
    id: '/api/public/hooks/record-topic-volume',
    path: '/api/public/hooks/record-topic-volume',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecheckViralEngagementRoute =
  ApiPublicHooksRecheckViralEngagementRouteImport.update({
    id: '/api/public/hooks/recheck-viral-engagement',
    path: '/api/public/hooks/recheck-viral-engagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPollGmailRoute = ApiPublicHooksPollGmailRouteImport.update({
  id: '/api/public/hooks/poll-gmail',
  path: '/api/public/hooks/poll-gmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMonitorTopicsRoute =
  ApiPublicHooksMonitorTopicsRouteImport.update({
    id: '/api/public/hooks/monitor-topics',
    path: '/api/public/hooks/monitor-topics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksListMonitoredTopicsRoute =
  ApiPublicHooksListMonitoredTopicsRouteImport.update({
    id: '/api/public/hooks/list-monitored-topics',
    path: '/api/public/hooks/list-monitored-topics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksListInstagramContentUrlsRoute =
  ApiPublicHooksListInstagramContentUrlsRouteImport.update({
    id: '/api/public/hooks/list-instagram-content-urls',
    path: '/api/public/hooks/list-instagram-content-urls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksListCrossSourceTrendsRoute =
  ApiPublicHooksListCrossSourceTrendsRouteImport.update({
    id: '/api/public/hooks/list-cross-source-trends',
    path: '/api/public/hooks/list-cross-source-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksListCanaliInspoTopicsRoute =
  ApiPublicHooksListCanaliInspoTopicsRouteImport.update({
    id: '/api/public/hooks/list-canali-inspo-topics',
    path: '/api/public/hooks/list-canali-inspo-topics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLinkPreviewRoute =
  ApiPublicHooksLinkPreviewRouteImport.update({
    id: '/api/public/hooks/link-preview',
    path: '/api/public/hooks/link-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksImportAspiBulkRoute =
  ApiPublicHooksImportAspiBulkRouteImport.update({
    id: '/api/public/hooks/import-aspi-bulk',
    path: '/api/public/hooks/import-aspi-bulk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGettySearchRoute =
  ApiPublicHooksGettySearchRouteImport.update({
    id: '/api/public/hooks/getty-search',
    path: '/api/public/hooks/getty-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFigmaImportRoute =
  ApiPublicHooksFigmaImportRouteImport.update({
    id: '/api/public/hooks/figma-import',
    path: '/api/public/hooks/figma-import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExtractKeywordsRoute =
  ApiPublicHooksExtractKeywordsRouteImport.update({
    id: '/api/public/hooks/extract-keywords',
    path: '/api/public/hooks/extract-keywords',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExportXlsxRoute =
  ApiPublicHooksExportXlsxRouteImport.update({
    id: '/api/public/hooks/export-xlsx',
    path: '/api/public/hooks/export-xlsx',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksExportFeedPptxRoute =
  ApiPublicHooksExportFeedPptxRouteImport.update({
    id: '/api/public/hooks/export-feed-pptx',
    path: '/api/public/hooks/export-feed-pptx',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeleteTrendSubmissionRoute =
  ApiPublicHooksDeleteTrendSubmissionRouteImport.update({
    id: '/api/public/hooks/delete-trend-submission',
    path: '/api/public/hooks/delete-trend-submission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeleteCanaleRoute =
  ApiPublicHooksDeleteCanaleRouteImport.update({
    id: '/api/public/hooks/delete-canale',
    path: '/api/public/hooks/delete-canale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckTokenHealthRoute =
  ApiPublicHooksCheckTokenHealthRouteImport.update({
    id: '/api/public/hooks/check-token-health',
    path: '/api/public/hooks/check-token-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApproveJobRoute =
  ApiPublicHooksApproveJobRouteImport.update({
    id: '/api/public/hooks/approve-job',
    path: '/api/public/hooks/approve-job',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAddClientChannelRoute =
  ApiPublicHooksAddClientChannelRouteImport.update({
    id: '/api/public/hooks/add-client-channel',
    path: '/api/public/hooks/add-client-channel',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/influencer-feed': typeof InfluencerFeedRoute
  '/linkedin': typeof LinkedinRoute
  '/tiktok-hashtag': typeof TiktokHashtagRoute
  '/trend-attuali': typeof TrendAttualiRoute
  '/trend-evergreen': typeof TrendEvergreenRoute
  '/trend-real-time': typeof TrendRealTimeRoute
  '/trend-virali': typeof TrendViraliRoute
  '/aspi-monitoring/$id': typeof AspiMonitoringIdRoute
  '/canali-inspo/$id': typeof CanaliInspoIdRoute
  '/collab-instagram/$username': typeof CollabInstagramUsernameRoute
  '/editor-grafico/$rubricaId': typeof EditorGraficoRubricaIdRoute
  '/influencer/$id': typeof InfluencerIdRoute
  '/aspi-monitoring/': typeof AspiMonitoringIndexRoute
  '/canali-inspo/': typeof CanaliInspoIndexRoute
  '/collab-instagram/': typeof CollabInstagramIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/piano-editoriale/': typeof PianoEditorialeIndexRoute
  '/reputazione-brand/': typeof ReputazioneBrandIndexRoute
  '/api/public/hooks/add-client-channel': typeof ApiPublicHooksAddClientChannelRoute
  '/api/public/hooks/approve-job': typeof ApiPublicHooksApproveJobRoute
  '/api/public/hooks/check-token-health': typeof ApiPublicHooksCheckTokenHealthRoute
  '/api/public/hooks/delete-canale': typeof ApiPublicHooksDeleteCanaleRoute
  '/api/public/hooks/delete-trend-submission': typeof ApiPublicHooksDeleteTrendSubmissionRoute
  '/api/public/hooks/export-feed-pptx': typeof ApiPublicHooksExportFeedPptxRoute
  '/api/public/hooks/export-xlsx': typeof ApiPublicHooksExportXlsxRoute
  '/api/public/hooks/extract-keywords': typeof ApiPublicHooksExtractKeywordsRoute
  '/api/public/hooks/figma-import': typeof ApiPublicHooksFigmaImportRoute
  '/api/public/hooks/getty-search': typeof ApiPublicHooksGettySearchRoute
  '/api/public/hooks/import-aspi-bulk': typeof ApiPublicHooksImportAspiBulkRoute
  '/api/public/hooks/link-preview': typeof ApiPublicHooksLinkPreviewRoute
  '/api/public/hooks/list-canali-inspo-topics': typeof ApiPublicHooksListCanaliInspoTopicsRoute
  '/api/public/hooks/list-cross-source-trends': typeof ApiPublicHooksListCrossSourceTrendsRoute
  '/api/public/hooks/list-instagram-content-urls': typeof ApiPublicHooksListInstagramContentUrlsRoute
  '/api/public/hooks/list-monitored-topics': typeof ApiPublicHooksListMonitoredTopicsRoute
  '/api/public/hooks/monitor-topics': typeof ApiPublicHooksMonitorTopicsRoute
  '/api/public/hooks/poll-gmail': typeof ApiPublicHooksPollGmailRoute
  '/api/public/hooks/recheck-viral-engagement': typeof ApiPublicHooksRecheckViralEngagementRoute
  '/api/public/hooks/record-topic-volume': typeof ApiPublicHooksRecordTopicVolumeRoute
  '/api/public/hooks/submit-manual': typeof ApiPublicHooksSubmitManualRoute
  '/api/public/hooks/sync-audio-trends': typeof ApiPublicHooksSyncAudioTrendsRoute
  '/api/public/hooks/sync-brand-mentions': typeof ApiPublicHooksSyncBrandMentionsRoute
  '/api/public/hooks/sync-cross-source-trends': typeof ApiPublicHooksSyncCrossSourceTrendsRoute
  '/api/public/hooks/sync-instagram-collab': typeof ApiPublicHooksSyncInstagramCollabRoute
  '/api/public/hooks/sync-tiktok-hashtag': typeof ApiPublicHooksSyncTiktokHashtagRoute
  '/api/public/hooks/sync-trending-hashtags': typeof ApiPublicHooksSyncTrendingHashtagsRoute
  '/api/public/hooks/sync-viral-trends': typeof ApiPublicHooksSyncViralTrendsRoute
  '/api/public/hooks/tiktok-hashtag-posts': typeof ApiPublicHooksTiktokHashtagPostsRoute
  '/api/public/hooks/tiktok-oembed': typeof ApiPublicHooksTiktokOembedRoute
  '/api/public/hooks/top-tiktok-hashtags': typeof ApiPublicHooksTopTiktokHashtagsRoute
  '/api/public/hooks/trigger-discovery-pipeline': typeof ApiPublicHooksTriggerDiscoveryPipelineRoute
  '/api/public/hooks/trigger-sync-aspi-monitoring': typeof ApiPublicHooksTriggerSyncAspiMonitoringRoute
  '/api/public/hooks/trigger-sync-canali-feed': typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/influencer-feed': typeof InfluencerFeedRoute
  '/linkedin': typeof LinkedinRoute
  '/tiktok-hashtag': typeof TiktokHashtagRoute
  '/trend-attuali': typeof TrendAttualiRoute
  '/trend-evergreen': typeof TrendEvergreenRoute
  '/trend-real-time': typeof TrendRealTimeRoute
  '/trend-virali': typeof TrendViraliRoute
  '/aspi-monitoring/$id': typeof AspiMonitoringIdRoute
  '/canali-inspo/$id': typeof CanaliInspoIdRoute
  '/collab-instagram/$username': typeof CollabInstagramUsernameRoute
  '/editor-grafico/$rubricaId': typeof EditorGraficoRubricaIdRoute
  '/influencer/$id': typeof InfluencerIdRoute
  '/aspi-monitoring': typeof AspiMonitoringIndexRoute
  '/canali-inspo': typeof CanaliInspoIndexRoute
  '/collab-instagram': typeof CollabInstagramIndexRoute
  '/feed': typeof FeedIndexRoute
  '/influencer': typeof InfluencerIndexRoute
  '/piano-editoriale': typeof PianoEditorialeIndexRoute
  '/reputazione-brand': typeof ReputazioneBrandIndexRoute
  '/api/public/hooks/add-client-channel': typeof ApiPublicHooksAddClientChannelRoute
  '/api/public/hooks/approve-job': typeof ApiPublicHooksApproveJobRoute
  '/api/public/hooks/check-token-health': typeof ApiPublicHooksCheckTokenHealthRoute
  '/api/public/hooks/delete-canale': typeof ApiPublicHooksDeleteCanaleRoute
  '/api/public/hooks/delete-trend-submission': typeof ApiPublicHooksDeleteTrendSubmissionRoute
  '/api/public/hooks/export-feed-pptx': typeof ApiPublicHooksExportFeedPptxRoute
  '/api/public/hooks/export-xlsx': typeof ApiPublicHooksExportXlsxRoute
  '/api/public/hooks/extract-keywords': typeof ApiPublicHooksExtractKeywordsRoute
  '/api/public/hooks/figma-import': typeof ApiPublicHooksFigmaImportRoute
  '/api/public/hooks/getty-search': typeof ApiPublicHooksGettySearchRoute
  '/api/public/hooks/import-aspi-bulk': typeof ApiPublicHooksImportAspiBulkRoute
  '/api/public/hooks/link-preview': typeof ApiPublicHooksLinkPreviewRoute
  '/api/public/hooks/list-canali-inspo-topics': typeof ApiPublicHooksListCanaliInspoTopicsRoute
  '/api/public/hooks/list-cross-source-trends': typeof ApiPublicHooksListCrossSourceTrendsRoute
  '/api/public/hooks/list-instagram-content-urls': typeof ApiPublicHooksListInstagramContentUrlsRoute
  '/api/public/hooks/list-monitored-topics': typeof ApiPublicHooksListMonitoredTopicsRoute
  '/api/public/hooks/monitor-topics': typeof ApiPublicHooksMonitorTopicsRoute
  '/api/public/hooks/poll-gmail': typeof ApiPublicHooksPollGmailRoute
  '/api/public/hooks/recheck-viral-engagement': typeof ApiPublicHooksRecheckViralEngagementRoute
  '/api/public/hooks/record-topic-volume': typeof ApiPublicHooksRecordTopicVolumeRoute
  '/api/public/hooks/submit-manual': typeof ApiPublicHooksSubmitManualRoute
  '/api/public/hooks/sync-audio-trends': typeof ApiPublicHooksSyncAudioTrendsRoute
  '/api/public/hooks/sync-brand-mentions': typeof ApiPublicHooksSyncBrandMentionsRoute
  '/api/public/hooks/sync-cross-source-trends': typeof ApiPublicHooksSyncCrossSourceTrendsRoute
  '/api/public/hooks/sync-instagram-collab': typeof ApiPublicHooksSyncInstagramCollabRoute
  '/api/public/hooks/sync-tiktok-hashtag': typeof ApiPublicHooksSyncTiktokHashtagRoute
  '/api/public/hooks/sync-trending-hashtags': typeof ApiPublicHooksSyncTrendingHashtagsRoute
  '/api/public/hooks/sync-viral-trends': typeof ApiPublicHooksSyncViralTrendsRoute
  '/api/public/hooks/tiktok-hashtag-posts': typeof ApiPublicHooksTiktokHashtagPostsRoute
  '/api/public/hooks/tiktok-oembed': typeof ApiPublicHooksTiktokOembedRoute
  '/api/public/hooks/top-tiktok-hashtags': typeof ApiPublicHooksTopTiktokHashtagsRoute
  '/api/public/hooks/trigger-discovery-pipeline': typeof ApiPublicHooksTriggerDiscoveryPipelineRoute
  '/api/public/hooks/trigger-sync-aspi-monitoring': typeof ApiPublicHooksTriggerSyncAspiMonitoringRoute
  '/api/public/hooks/trigger-sync-canali-feed': typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/influencer-feed': typeof InfluencerFeedRoute
  '/linkedin': typeof LinkedinRoute
  '/tiktok-hashtag': typeof TiktokHashtagRoute
  '/trend-attuali': typeof TrendAttualiRoute
  '/trend-evergreen': typeof TrendEvergreenRoute
  '/trend-real-time': typeof TrendRealTimeRoute
  '/trend-virali': typeof TrendViraliRoute
  '/aspi-monitoring/$id': typeof AspiMonitoringIdRoute
  '/canali-inspo/$id': typeof CanaliInspoIdRoute
  '/collab-instagram/$username': typeof CollabInstagramUsernameRoute
  '/editor-grafico/$rubricaId': typeof EditorGraficoRubricaIdRoute
  '/influencer/$id': typeof InfluencerIdRoute
  '/aspi-monitoring/': typeof AspiMonitoringIndexRoute
  '/canali-inspo/': typeof CanaliInspoIndexRoute
  '/collab-instagram/': typeof CollabInstagramIndexRoute
  '/feed/': typeof FeedIndexRoute
  '/influencer/': typeof InfluencerIndexRoute
  '/piano-editoriale/': typeof PianoEditorialeIndexRoute
  '/reputazione-brand/': typeof ReputazioneBrandIndexRoute
  '/api/public/hooks/add-client-channel': typeof ApiPublicHooksAddClientChannelRoute
  '/api/public/hooks/approve-job': typeof ApiPublicHooksApproveJobRoute
  '/api/public/hooks/check-token-health': typeof ApiPublicHooksCheckTokenHealthRoute
  '/api/public/hooks/delete-canale': typeof ApiPublicHooksDeleteCanaleRoute
  '/api/public/hooks/delete-trend-submission': typeof ApiPublicHooksDeleteTrendSubmissionRoute
  '/api/public/hooks/export-feed-pptx': typeof ApiPublicHooksExportFeedPptxRoute
  '/api/public/hooks/export-xlsx': typeof ApiPublicHooksExportXlsxRoute
  '/api/public/hooks/extract-keywords': typeof ApiPublicHooksExtractKeywordsRoute
  '/api/public/hooks/figma-import': typeof ApiPublicHooksFigmaImportRoute
  '/api/public/hooks/getty-search': typeof ApiPublicHooksGettySearchRoute
  '/api/public/hooks/import-aspi-bulk': typeof ApiPublicHooksImportAspiBulkRoute
  '/api/public/hooks/link-preview': typeof ApiPublicHooksLinkPreviewRoute
  '/api/public/hooks/list-canali-inspo-topics': typeof ApiPublicHooksListCanaliInspoTopicsRoute
  '/api/public/hooks/list-cross-source-trends': typeof ApiPublicHooksListCrossSourceTrendsRoute
  '/api/public/hooks/list-instagram-content-urls': typeof ApiPublicHooksListInstagramContentUrlsRoute
  '/api/public/hooks/list-monitored-topics': typeof ApiPublicHooksListMonitoredTopicsRoute
  '/api/public/hooks/monitor-topics': typeof ApiPublicHooksMonitorTopicsRoute
  '/api/public/hooks/poll-gmail': typeof ApiPublicHooksPollGmailRoute
  '/api/public/hooks/recheck-viral-engagement': typeof ApiPublicHooksRecheckViralEngagementRoute
  '/api/public/hooks/record-topic-volume': typeof ApiPublicHooksRecordTopicVolumeRoute
  '/api/public/hooks/submit-manual': typeof ApiPublicHooksSubmitManualRoute
  '/api/public/hooks/sync-audio-trends': typeof ApiPublicHooksSyncAudioTrendsRoute
  '/api/public/hooks/sync-brand-mentions': typeof ApiPublicHooksSyncBrandMentionsRoute
  '/api/public/hooks/sync-cross-source-trends': typeof ApiPublicHooksSyncCrossSourceTrendsRoute
  '/api/public/hooks/sync-instagram-collab': typeof ApiPublicHooksSyncInstagramCollabRoute
  '/api/public/hooks/sync-tiktok-hashtag': typeof ApiPublicHooksSyncTiktokHashtagRoute
  '/api/public/hooks/sync-trending-hashtags': typeof ApiPublicHooksSyncTrendingHashtagsRoute
  '/api/public/hooks/sync-viral-trends': typeof ApiPublicHooksSyncViralTrendsRoute
  '/api/public/hooks/tiktok-hashtag-posts': typeof ApiPublicHooksTiktokHashtagPostsRoute
  '/api/public/hooks/tiktok-oembed': typeof ApiPublicHooksTiktokOembedRoute
  '/api/public/hooks/top-tiktok-hashtags': typeof ApiPublicHooksTopTiktokHashtagsRoute
  '/api/public/hooks/trigger-discovery-pipeline': typeof ApiPublicHooksTriggerDiscoveryPipelineRoute
  '/api/public/hooks/trigger-sync-aspi-monitoring': typeof ApiPublicHooksTriggerSyncAspiMonitoringRoute
  '/api/public/hooks/trigger-sync-canali-feed': typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/influencer-feed'
    | '/linkedin'
    | '/tiktok-hashtag'
    | '/trend-attuali'
    | '/trend-evergreen'
    | '/trend-real-time'
    | '/trend-virali'
    | '/aspi-monitoring/$id'
    | '/canali-inspo/$id'
    | '/collab-instagram/$username'
    | '/editor-grafico/$rubricaId'
    | '/influencer/$id'
    | '/aspi-monitoring/'
    | '/canali-inspo/'
    | '/collab-instagram/'
    | '/feed/'
    | '/influencer/'
    | '/piano-editoriale/'
    | '/reputazione-brand/'
    | '/api/public/hooks/add-client-channel'
    | '/api/public/hooks/approve-job'
    | '/api/public/hooks/check-token-health'
    | '/api/public/hooks/delete-canale'
    | '/api/public/hooks/delete-trend-submission'
    | '/api/public/hooks/export-feed-pptx'
    | '/api/public/hooks/export-xlsx'
    | '/api/public/hooks/extract-keywords'
    | '/api/public/hooks/figma-import'
    | '/api/public/hooks/getty-search'
    | '/api/public/hooks/import-aspi-bulk'
    | '/api/public/hooks/link-preview'
    | '/api/public/hooks/list-canali-inspo-topics'
    | '/api/public/hooks/list-cross-source-trends'
    | '/api/public/hooks/list-instagram-content-urls'
    | '/api/public/hooks/list-monitored-topics'
    | '/api/public/hooks/monitor-topics'
    | '/api/public/hooks/poll-gmail'
    | '/api/public/hooks/recheck-viral-engagement'
    | '/api/public/hooks/record-topic-volume'
    | '/api/public/hooks/submit-manual'
    | '/api/public/hooks/sync-audio-trends'
    | '/api/public/hooks/sync-brand-mentions'
    | '/api/public/hooks/sync-cross-source-trends'
    | '/api/public/hooks/sync-instagram-collab'
    | '/api/public/hooks/sync-tiktok-hashtag'
    | '/api/public/hooks/sync-trending-hashtags'
    | '/api/public/hooks/sync-viral-trends'
    | '/api/public/hooks/tiktok-hashtag-posts'
    | '/api/public/hooks/tiktok-oembed'
    | '/api/public/hooks/top-tiktok-hashtags'
    | '/api/public/hooks/trigger-discovery-pipeline'
    | '/api/public/hooks/trigger-sync-aspi-monitoring'
    | '/api/public/hooks/trigger-sync-canali-feed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/influencer-feed'
    | '/linkedin'
    | '/tiktok-hashtag'
    | '/trend-attuali'
    | '/trend-evergreen'
    | '/trend-real-time'
    | '/trend-virali'
    | '/aspi-monitoring/$id'
    | '/canali-inspo/$id'
    | '/collab-instagram/$username'
    | '/editor-grafico/$rubricaId'
    | '/influencer/$id'
    | '/aspi-monitoring'
    | '/canali-inspo'
    | '/collab-instagram'
    | '/feed'
    | '/influencer'
    | '/piano-editoriale'
    | '/reputazione-brand'
    | '/api/public/hooks/add-client-channel'
    | '/api/public/hooks/approve-job'
    | '/api/public/hooks/check-token-health'
    | '/api/public/hooks/delete-canale'
    | '/api/public/hooks/delete-trend-submission'
    | '/api/public/hooks/export-feed-pptx'
    | '/api/public/hooks/export-xlsx'
    | '/api/public/hooks/extract-keywords'
    | '/api/public/hooks/figma-import'
    | '/api/public/hooks/getty-search'
    | '/api/public/hooks/import-aspi-bulk'
    | '/api/public/hooks/link-preview'
    | '/api/public/hooks/list-canali-inspo-topics'
    | '/api/public/hooks/list-cross-source-trends'
    | '/api/public/hooks/list-instagram-content-urls'
    | '/api/public/hooks/list-monitored-topics'
    | '/api/public/hooks/monitor-topics'
    | '/api/public/hooks/poll-gmail'
    | '/api/public/hooks/recheck-viral-engagement'
    | '/api/public/hooks/record-topic-volume'
    | '/api/public/hooks/submit-manual'
    | '/api/public/hooks/sync-audio-trends'
    | '/api/public/hooks/sync-brand-mentions'
    | '/api/public/hooks/sync-cross-source-trends'
    | '/api/public/hooks/sync-instagram-collab'
    | '/api/public/hooks/sync-tiktok-hashtag'
    | '/api/public/hooks/sync-trending-hashtags'
    | '/api/public/hooks/sync-viral-trends'
    | '/api/public/hooks/tiktok-hashtag-posts'
    | '/api/public/hooks/tiktok-oembed'
    | '/api/public/hooks/top-tiktok-hashtags'
    | '/api/public/hooks/trigger-discovery-pipeline'
    | '/api/public/hooks/trigger-sync-aspi-monitoring'
    | '/api/public/hooks/trigger-sync-canali-feed'
  id:
    | '__root__'
    | '/'
    | '/influencer-feed'
    | '/linkedin'
    | '/tiktok-hashtag'
    | '/trend-attuali'
    | '/trend-evergreen'
    | '/trend-real-time'
    | '/trend-virali'
    | '/aspi-monitoring/$id'
    | '/canali-inspo/$id'
    | '/collab-instagram/$username'
    | '/editor-grafico/$rubricaId'
    | '/influencer/$id'
    | '/aspi-monitoring/'
    | '/canali-inspo/'
    | '/collab-instagram/'
    | '/feed/'
    | '/influencer/'
    | '/piano-editoriale/'
    | '/reputazione-brand/'
    | '/api/public/hooks/add-client-channel'
    | '/api/public/hooks/approve-job'
    | '/api/public/hooks/check-token-health'
    | '/api/public/hooks/delete-canale'
    | '/api/public/hooks/delete-trend-submission'
    | '/api/public/hooks/export-feed-pptx'
    | '/api/public/hooks/export-xlsx'
    | '/api/public/hooks/extract-keywords'
    | '/api/public/hooks/figma-import'
    | '/api/public/hooks/getty-search'
    | '/api/public/hooks/import-aspi-bulk'
    | '/api/public/hooks/link-preview'
    | '/api/public/hooks/list-canali-inspo-topics'
    | '/api/public/hooks/list-cross-source-trends'
    | '/api/public/hooks/list-instagram-content-urls'
    | '/api/public/hooks/list-monitored-topics'
    | '/api/public/hooks/monitor-topics'
    | '/api/public/hooks/poll-gmail'
    | '/api/public/hooks/recheck-viral-engagement'
    | '/api/public/hooks/record-topic-volume'
    | '/api/public/hooks/submit-manual'
    | '/api/public/hooks/sync-audio-trends'
    | '/api/public/hooks/sync-brand-mentions'
    | '/api/public/hooks/sync-cross-source-trends'
    | '/api/public/hooks/sync-instagram-collab'
    | '/api/public/hooks/sync-tiktok-hashtag'
    | '/api/public/hooks/sync-trending-hashtags'
    | '/api/public/hooks/sync-viral-trends'
    | '/api/public/hooks/tiktok-hashtag-posts'
    | '/api/public/hooks/tiktok-oembed'
    | '/api/public/hooks/top-tiktok-hashtags'
    | '/api/public/hooks/trigger-discovery-pipeline'
    | '/api/public/hooks/trigger-sync-aspi-monitoring'
    | '/api/public/hooks/trigger-sync-canali-feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfluencerFeedRoute: typeof InfluencerFeedRoute
  LinkedinRoute: typeof LinkedinRoute
  TiktokHashtagRoute: typeof TiktokHashtagRoute
  TrendAttualiRoute: typeof TrendAttualiRoute
  TrendEvergreenRoute: typeof TrendEvergreenRoute
  TrendRealTimeRoute: typeof TrendRealTimeRoute
  TrendViraliRoute: typeof TrendViraliRoute
  AspiMonitoringIdRoute: typeof AspiMonitoringIdRoute
  CanaliInspoIdRoute: typeof CanaliInspoIdRoute
  CollabInstagramUsernameRoute: typeof CollabInstagramUsernameRoute
  EditorGraficoRubricaIdRoute: typeof EditorGraficoRubricaIdRoute
  InfluencerIdRoute: typeof InfluencerIdRoute
  AspiMonitoringIndexRoute: typeof AspiMonitoringIndexRoute
  CanaliInspoIndexRoute: typeof CanaliInspoIndexRoute
  CollabInstagramIndexRoute: typeof CollabInstagramIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  InfluencerIndexRoute: typeof InfluencerIndexRoute
  PianoEditorialeIndexRoute: typeof PianoEditorialeIndexRoute
  ReputazioneBrandIndexRoute: typeof ReputazioneBrandIndexRoute
  ApiPublicHooksAddClientChannelRoute: typeof ApiPublicHooksAddClientChannelRoute
  ApiPublicHooksApproveJobRoute: typeof ApiPublicHooksApproveJobRoute
  ApiPublicHooksCheckTokenHealthRoute: typeof ApiPublicHooksCheckTokenHealthRoute
  ApiPublicHooksDeleteCanaleRoute: typeof ApiPublicHooksDeleteCanaleRoute
  ApiPublicHooksDeleteTrendSubmissionRoute: typeof ApiPublicHooksDeleteTrendSubmissionRoute
  ApiPublicHooksExportFeedPptxRoute: typeof ApiPublicHooksExportFeedPptxRoute
  ApiPublicHooksExportXlsxRoute: typeof ApiPublicHooksExportXlsxRoute
  ApiPublicHooksExtractKeywordsRoute: typeof ApiPublicHooksExtractKeywordsRoute
  ApiPublicHooksFigmaImportRoute: typeof ApiPublicHooksFigmaImportRoute
  ApiPublicHooksGettySearchRoute: typeof ApiPublicHooksGettySearchRoute
  ApiPublicHooksImportAspiBulkRoute: typeof ApiPublicHooksImportAspiBulkRoute
  ApiPublicHooksLinkPreviewRoute: typeof ApiPublicHooksLinkPreviewRoute
  ApiPublicHooksListCanaliInspoTopicsRoute: typeof ApiPublicHooksListCanaliInspoTopicsRoute
  ApiPublicHooksListCrossSourceTrendsRoute: typeof ApiPublicHooksListCrossSourceTrendsRoute
  ApiPublicHooksListInstagramContentUrlsRoute: typeof ApiPublicHooksListInstagramContentUrlsRoute
  ApiPublicHooksListMonitoredTopicsRoute: typeof ApiPublicHooksListMonitoredTopicsRoute
  ApiPublicHooksMonitorTopicsRoute: typeof ApiPublicHooksMonitorTopicsRoute
  ApiPublicHooksPollGmailRoute: typeof ApiPublicHooksPollGmailRoute
  ApiPublicHooksRecheckViralEngagementRoute: typeof ApiPublicHooksRecheckViralEngagementRoute
  ApiPublicHooksRecordTopicVolumeRoute: typeof ApiPublicHooksRecordTopicVolumeRoute
  ApiPublicHooksSubmitManualRoute: typeof ApiPublicHooksSubmitManualRoute
  ApiPublicHooksSyncAudioTrendsRoute: typeof ApiPublicHooksSyncAudioTrendsRoute
  ApiPublicHooksSyncBrandMentionsRoute: typeof ApiPublicHooksSyncBrandMentionsRoute
  ApiPublicHooksSyncCrossSourceTrendsRoute: typeof ApiPublicHooksSyncCrossSourceTrendsRoute
  ApiPublicHooksSyncInstagramCollabRoute: typeof ApiPublicHooksSyncInstagramCollabRoute
  ApiPublicHooksSyncTiktokHashtagRoute: typeof ApiPublicHooksSyncTiktokHashtagRoute
  ApiPublicHooksSyncTrendingHashtagsRoute: typeof ApiPublicHooksSyncTrendingHashtagsRoute
  ApiPublicHooksSyncViralTrendsRoute: typeof ApiPublicHooksSyncViralTrendsRoute
  ApiPublicHooksTiktokHashtagPostsRoute: typeof ApiPublicHooksTiktokHashtagPostsRoute
  ApiPublicHooksTiktokOembedRoute: typeof ApiPublicHooksTiktokOembedRoute
  ApiPublicHooksTopTiktokHashtagsRoute: typeof ApiPublicHooksTopTiktokHashtagsRoute
  ApiPublicHooksTriggerDiscoveryPipelineRoute: typeof ApiPublicHooksTriggerDiscoveryPipelineRoute
  ApiPublicHooksTriggerSyncAspiMonitoringRoute: typeof ApiPublicHooksTriggerSyncAspiMonitoringRoute
  ApiPublicHooksTriggerSyncCanaliFeedRoute: typeof ApiPublicHooksTriggerSyncCanaliFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trend-virali': {
      id: '/trend-virali'
      path: '/trend-virali'
      fullPath: '/trend-virali'
      preLoaderRoute: typeof TrendViraliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-real-time': {
      id: '/trend-real-time'
      path: '/trend-real-time'
      fullPath: '/trend-real-time'
      preLoaderRoute: typeof TrendRealTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-evergreen': {
      id: '/trend-evergreen'
      path: '/trend-evergreen'
      fullPath: '/trend-evergreen'
      preLoaderRoute: typeof TrendEvergreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-attuali': {
      id: '/trend-attuali'
      path: '/trend-attuali'
      fullPath: '/trend-attuali'
      preLoaderRoute: typeof TrendAttualiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-hashtag': {
      id: '/tiktok-hashtag'
      path: '/tiktok-hashtag'
      fullPath: '/tiktok-hashtag'
      preLoaderRoute: typeof TiktokHashtagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer-feed': {
      id: '/influencer-feed'
      path: '/influencer-feed'
      fullPath: '/influencer-feed'
      preLoaderRoute: typeof InfluencerFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reputazione-brand/': {
      id: '/reputazione-brand/'
      path: '/reputazione-brand'
      fullPath: '/reputazione-brand/'
      preLoaderRoute: typeof ReputazioneBrandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano-editoriale/': {
      id: '/piano-editoriale/'
      path: '/piano-editoriale'
      fullPath: '/piano-editoriale/'
      preLoaderRoute: typeof PianoEditorialeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/': {
      id: '/influencer/'
      path: '/influencer'
      fullPath: '/influencer/'
      preLoaderRoute: typeof InfluencerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/': {
      id: '/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab-instagram/': {
      id: '/collab-instagram/'
      path: '/collab-instagram'
      fullPath: '/collab-instagram/'
      preLoaderRoute: typeof CollabInstagramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canali-inspo/': {
      id: '/canali-inspo/'
      path: '/canali-inspo'
      fullPath: '/canali-inspo/'
      preLoaderRoute: typeof CanaliInspoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspi-monitoring/': {
      id: '/aspi-monitoring/'
      path: '/aspi-monitoring'
      fullPath: '/aspi-monitoring/'
      preLoaderRoute: typeof AspiMonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer/$id': {
      id: '/influencer/$id'
      path: '/influencer/$id'
      fullPath: '/influencer/$id'
      preLoaderRoute: typeof InfluencerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor-grafico/$rubricaId': {
      id: '/editor-grafico/$rubricaId'
      path: '/editor-grafico/$rubricaId'
      fullPath: '/editor-grafico/$rubricaId'
      preLoaderRoute: typeof EditorGraficoRubricaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab-instagram/$username': {
      id: '/collab-instagram/$username'
      path: '/collab-instagram/$username'
      fullPath: '/collab-instagram/$username'
      preLoaderRoute: typeof CollabInstagramUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canali-inspo/$id': {
      id: '/canali-inspo/$id'
      path: '/canali-inspo/$id'
      fullPath: '/canali-inspo/$id'
      preLoaderRoute: typeof CanaliInspoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aspi-monitoring/$id': {
      id: '/aspi-monitoring/$id'
      path: '/aspi-monitoring/$id'
      fullPath: '/aspi-monitoring/$id'
      preLoaderRoute: typeof AspiMonitoringIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trigger-sync-canali-feed': {
      id: '/api/public/hooks/trigger-sync-canali-feed'
      path: '/api/public/hooks/trigger-sync-canali-feed'
      fullPath: '/api/public/hooks/trigger-sync-canali-feed'
      preLoaderRoute: typeof ApiPublicHooksTriggerSyncCanaliFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trigger-sync-aspi-monitoring': {
      id: '/api/public/hooks/trigger-sync-aspi-monitoring'
      path: '/api/public/hooks/trigger-sync-aspi-monitoring'
      fullPath: '/api/public/hooks/trigger-sync-aspi-monitoring'
      preLoaderRoute: typeof ApiPublicHooksTriggerSyncAspiMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trigger-discovery-pipeline': {
      id: '/api/public/hooks/trigger-discovery-pipeline'
      path: '/api/public/hooks/trigger-discovery-pipeline'
      fullPath: '/api/public/hooks/trigger-discovery-pipeline'
      preLoaderRoute: typeof ApiPublicHooksTriggerDiscoveryPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/top-tiktok-hashtags': {
      id: '/api/public/hooks/top-tiktok-hashtags'
      path: '/api/public/hooks/top-tiktok-hashtags'
      fullPath: '/api/public/hooks/top-tiktok-hashtags'
      preLoaderRoute: typeof ApiPublicHooksTopTiktokHashtagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tiktok-oembed': {
      id: '/api/public/hooks/tiktok-oembed'
      path: '/api/public/hooks/tiktok-oembed'
      fullPath: '/api/public/hooks/tiktok-oembed'
      preLoaderRoute: typeof ApiPublicHooksTiktokOembedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tiktok-hashtag-posts': {
      id: '/api/public/hooks/tiktok-hashtag-posts'
      path: '/api/public/hooks/tiktok-hashtag-posts'
      fullPath: '/api/public/hooks/tiktok-hashtag-posts'
      preLoaderRoute: typeof ApiPublicHooksTiktokHashtagPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-viral-trends': {
      id: '/api/public/hooks/sync-viral-trends'
      path: '/api/public/hooks/sync-viral-trends'
      fullPath: '/api/public/hooks/sync-viral-trends'
      preLoaderRoute: typeof ApiPublicHooksSyncViralTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-trending-hashtags': {
      id: '/api/public/hooks/sync-trending-hashtags'
      path: '/api/public/hooks/sync-trending-hashtags'
      fullPath: '/api/public/hooks/sync-trending-hashtags'
      preLoaderRoute: typeof ApiPublicHooksSyncTrendingHashtagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-tiktok-hashtag': {
      id: '/api/public/hooks/sync-tiktok-hashtag'
      path: '/api/public/hooks/sync-tiktok-hashtag'
      fullPath: '/api/public/hooks/sync-tiktok-hashtag'
      preLoaderRoute: typeof ApiPublicHooksSyncTiktokHashtagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-instagram-collab': {
      id: '/api/public/hooks/sync-instagram-collab'
      path: '/api/public/hooks/sync-instagram-collab'
      fullPath: '/api/public/hooks/sync-instagram-collab'
      preLoaderRoute: typeof ApiPublicHooksSyncInstagramCollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-cross-source-trends': {
      id: '/api/public/hooks/sync-cross-source-trends'
      path: '/api/public/hooks/sync-cross-source-trends'
      fullPath: '/api/public/hooks/sync-cross-source-trends'
      preLoaderRoute: typeof ApiPublicHooksSyncCrossSourceTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-brand-mentions': {
      id: '/api/public/hooks/sync-brand-mentions'
      path: '/api/public/hooks/sync-brand-mentions'
      fullPath: '/api/public/hooks/sync-brand-mentions'
      preLoaderRoute: typeof ApiPublicHooksSyncBrandMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-audio-trends': {
      id: '/api/public/hooks/sync-audio-trends'
      path: '/api/public/hooks/sync-audio-trends'
      fullPath: '/api/public/hooks/sync-audio-trends'
      preLoaderRoute: typeof ApiPublicHooksSyncAudioTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/submit-manual': {
      id: '/api/public/hooks/submit-manual'
      path: '/api/public/hooks/submit-manual'
      fullPath: '/api/public/hooks/submit-manual'
      preLoaderRoute: typeof ApiPublicHooksSubmitManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/record-topic-volume': {
      id: '/api/public/hooks/record-topic-volume'
      path: '/api/public/hooks/record-topic-volume'
      fullPath: '/api/public/hooks/record-topic-volume'
      preLoaderRoute: typeof ApiPublicHooksRecordTopicVolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recheck-viral-engagement': {
      id: '/api/public/hooks/recheck-viral-engagement'
      path: '/api/public/hooks/recheck-viral-engagement'
      fullPath: '/api/public/hooks/recheck-viral-engagement'
      preLoaderRoute: typeof ApiPublicHooksRecheckViralEngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/poll-gmail': {
      id: '/api/public/hooks/poll-gmail'
      path: '/api/public/hooks/poll-gmail'
      fullPath: '/api/public/hooks/poll-gmail'
      preLoaderRoute: typeof ApiPublicHooksPollGmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-topics': {
      id: '/api/public/hooks/monitor-topics'
      path: '/api/public/hooks/monitor-topics'
      fullPath: '/api/public/hooks/monitor-topics'
      preLoaderRoute: typeof ApiPublicHooksMonitorTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/list-monitored-topics': {
      id: '/api/public/hooks/list-monitored-topics'
      path: '/api/public/hooks/list-monitored-topics'
      fullPath: '/api/public/hooks/list-monitored-topics'
      preLoaderRoute: typeof ApiPublicHooksListMonitoredTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/list-instagram-content-urls': {
      id: '/api/public/hooks/list-instagram-content-urls'
      path: '/api/public/hooks/list-instagram-content-urls'
      fullPath: '/api/public/hooks/list-instagram-content-urls'
      preLoaderRoute: typeof ApiPublicHooksListInstagramContentUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/list-cross-source-trends': {
      id: '/api/public/hooks/list-cross-source-trends'
      path: '/api/public/hooks/list-cross-source-trends'
      fullPath: '/api/public/hooks/list-cross-source-trends'
      preLoaderRoute: typeof ApiPublicHooksListCrossSourceTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/list-canali-inspo-topics': {
      id: '/api/public/hooks/list-canali-inspo-topics'
      path: '/api/public/hooks/list-canali-inspo-topics'
      fullPath: '/api/public/hooks/list-canali-inspo-topics'
      preLoaderRoute: typeof ApiPublicHooksListCanaliInspoTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/link-preview': {
      id: '/api/public/hooks/link-preview'
      path: '/api/public/hooks/link-preview'
      fullPath: '/api/public/hooks/link-preview'
      preLoaderRoute: typeof ApiPublicHooksLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-aspi-bulk': {
      id: '/api/public/hooks/import-aspi-bulk'
      path: '/api/public/hooks/import-aspi-bulk'
      fullPath: '/api/public/hooks/import-aspi-bulk'
      preLoaderRoute: typeof ApiPublicHooksImportAspiBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/getty-search': {
      id: '/api/public/hooks/getty-search'
      path: '/api/public/hooks/getty-search'
      fullPath: '/api/public/hooks/getty-search'
      preLoaderRoute: typeof ApiPublicHooksGettySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/figma-import': {
      id: '/api/public/hooks/figma-import'
      path: '/api/public/hooks/figma-import'
      fullPath: '/api/public/hooks/figma-import'
      preLoaderRoute: typeof ApiPublicHooksFigmaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/extract-keywords': {
      id: '/api/public/hooks/extract-keywords'
      path: '/api/public/hooks/extract-keywords'
      fullPath: '/api/public/hooks/extract-keywords'
      preLoaderRoute: typeof ApiPublicHooksExtractKeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/export-xlsx': {
      id: '/api/public/hooks/export-xlsx'
      path: '/api/public/hooks/export-xlsx'
      fullPath: '/api/public/hooks/export-xlsx'
      preLoaderRoute: typeof ApiPublicHooksExportXlsxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/export-feed-pptx': {
      id: '/api/public/hooks/export-feed-pptx'
      path: '/api/public/hooks/export-feed-pptx'
      fullPath: '/api/public/hooks/export-feed-pptx'
      preLoaderRoute: typeof ApiPublicHooksExportFeedPptxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/delete-trend-submission': {
      id: '/api/public/hooks/delete-trend-submission'
      path: '/api/public/hooks/delete-trend-submission'
      fullPath: '/api/public/hooks/delete-trend-submission'
      preLoaderRoute: typeof ApiPublicHooksDeleteTrendSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/delete-canale': {
      id: '/api/public/hooks/delete-canale'
      path: '/api/public/hooks/delete-canale'
      fullPath: '/api/public/hooks/delete-canale'
      preLoaderRoute: typeof ApiPublicHooksDeleteCanaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-token-health': {
      id: '/api/public/hooks/check-token-health'
      path: '/api/public/hooks/check-token-health'
      fullPath: '/api/public/hooks/check-token-health'
      preLoaderRoute: typeof ApiPublicHooksCheckTokenHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/approve-job': {
      id: '/api/public/hooks/approve-job'
      path: '/api/public/hooks/approve-job'
      fullPath: '/api/public/hooks/approve-job'
      preLoaderRoute: typeof ApiPublicHooksApproveJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/add-client-channel': {
      id: '/api/public/hooks/add-client-channel'
      path: '/api/public/hooks/add-client-channel'
      fullPath: '/api/public/hooks/add-client-channel'
      preLoaderRoute: typeof ApiPublicHooksAddClientChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfluencerFeedRoute: InfluencerFeedRoute,
  LinkedinRoute: LinkedinRoute,
  TiktokHashtagRoute: TiktokHashtagRoute,
  TrendAttualiRoute: TrendAttualiRoute,
  TrendEvergreenRoute: TrendEvergreenRoute,
  TrendRealTimeRoute: TrendRealTimeRoute,
  TrendViraliRoute: TrendViraliRoute,
  AspiMonitoringIdRoute: AspiMonitoringIdRoute,
  CanaliInspoIdRoute: CanaliInspoIdRoute,
  CollabInstagramUsernameRoute: CollabInstagramUsernameRoute,
  EditorGraficoRubricaIdRoute: EditorGraficoRubricaIdRoute,
  InfluencerIdRoute: InfluencerIdRoute,
  AspiMonitoringIndexRoute: AspiMonitoringIndexRoute,
  CanaliInspoIndexRoute: CanaliInspoIndexRoute,
  CollabInstagramIndexRoute: CollabInstagramIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  InfluencerIndexRoute: InfluencerIndexRoute,
  PianoEditorialeIndexRoute: PianoEditorialeIndexRoute,
  ReputazioneBrandIndexRoute: ReputazioneBrandIndexRoute,
  ApiPublicHooksAddClientChannelRoute: ApiPublicHooksAddClientChannelRoute,
  ApiPublicHooksApproveJobRoute: ApiPublicHooksApproveJobRoute,
  ApiPublicHooksCheckTokenHealthRoute: ApiPublicHooksCheckTokenHealthRoute,
  ApiPublicHooksDeleteCanaleRoute: ApiPublicHooksDeleteCanaleRoute,
  ApiPublicHooksDeleteTrendSubmissionRoute:
    ApiPublicHooksDeleteTrendSubmissionRoute,
  ApiPublicHooksExportFeedPptxRoute: ApiPublicHooksExportFeedPptxRoute,
  ApiPublicHooksExportXlsxRoute: ApiPublicHooksExportXlsxRoute,
  ApiPublicHooksExtractKeywordsRoute: ApiPublicHooksExtractKeywordsRoute,
  ApiPublicHooksFigmaImportRoute: ApiPublicHooksFigmaImportRoute,
  ApiPublicHooksGettySearchRoute: ApiPublicHooksGettySearchRoute,
  ApiPublicHooksImportAspiBulkRoute: ApiPublicHooksImportAspiBulkRoute,
  ApiPublicHooksLinkPreviewRoute: ApiPublicHooksLinkPreviewRoute,
  ApiPublicHooksListCanaliInspoTopicsRoute:
    ApiPublicHooksListCanaliInspoTopicsRoute,
  ApiPublicHooksListCrossSourceTrendsRoute:
    ApiPublicHooksListCrossSourceTrendsRoute,
  ApiPublicHooksListInstagramContentUrlsRoute:
    ApiPublicHooksListInstagramContentUrlsRoute,
  ApiPublicHooksListMonitoredTopicsRoute:
    ApiPublicHooksListMonitoredTopicsRoute,
  ApiPublicHooksMonitorTopicsRoute: ApiPublicHooksMonitorTopicsRoute,
  ApiPublicHooksPollGmailRoute: ApiPublicHooksPollGmailRoute,
  ApiPublicHooksRecheckViralEngagementRoute:
    ApiPublicHooksRecheckViralEngagementRoute,
  ApiPublicHooksRecordTopicVolumeRoute: ApiPublicHooksRecordTopicVolumeRoute,
  ApiPublicHooksSubmitManualRoute: ApiPublicHooksSubmitManualRoute,
  ApiPublicHooksSyncAudioTrendsRoute: ApiPublicHooksSyncAudioTrendsRoute,
  ApiPublicHooksSyncBrandMentionsRoute: ApiPublicHooksSyncBrandMentionsRoute,
  ApiPublicHooksSyncCrossSourceTrendsRoute:
    ApiPublicHooksSyncCrossSourceTrendsRoute,
  ApiPublicHooksSyncInstagramCollabRoute:
    ApiPublicHooksSyncInstagramCollabRoute,
  ApiPublicHooksSyncTiktokHashtagRoute: ApiPublicHooksSyncTiktokHashtagRoute,
  ApiPublicHooksSyncTrendingHashtagsRoute:
    ApiPublicHooksSyncTrendingHashtagsRoute,
  ApiPublicHooksSyncViralTrendsRoute: ApiPublicHooksSyncViralTrendsRoute,
  ApiPublicHooksTiktokHashtagPostsRoute: ApiPublicHooksTiktokHashtagPostsRoute,
  ApiPublicHooksTiktokOembedRoute: ApiPublicHooksTiktokOembedRoute,
  ApiPublicHooksTopTiktokHashtagsRoute: ApiPublicHooksTopTiktokHashtagsRoute,
  ApiPublicHooksTriggerDiscoveryPipelineRoute:
    ApiPublicHooksTriggerDiscoveryPipelineRoute,
  ApiPublicHooksTriggerSyncAspiMonitoringRoute:
    ApiPublicHooksTriggerSyncAspiMonitoringRoute,
  ApiPublicHooksTriggerSyncCanaliFeedRoute:
    ApiPublicHooksTriggerSyncCanaliFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
